# Generated by Django 5.1.3 on 2024-12-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="message",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
            ],
        ),
    ]
