# Generated by Django 5.1.3 on 2024-12-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_message_is_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="estimated_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
